name: Build and Test

on:
  push:
    branches: [ master ]
    tags-ignore:
    - 'v*'
  pull_request:
    branches: [ master ]

permissions: read-all

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0
    - name: apt
      run: sudo apt-get update && apt-get install gcc autoconf bison gettext autopoint help2man lzip texinfo texlive
    - name: autogen
      run: ./autogen.sh
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
